use_frameworks!

target 'InfiniteLayout_Example' do
  pod 'InfiniteLayout', :path => '../'
  pod 'InfiniteLayout/Rx', :path => '../'

  target 'InfiniteLayout_Tests' do
    inherit! :search_paths

    
  end
end
